language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - wget -P Tests/Unit/ http://downloads.atoum.org/nightly/mageekguy.atoum.phar

script: php Tests/Unit/mageekguy.atoum.phar -d Tests/Unit/

notifications:
  disabled: true